function insertPreinspectionReportQuery() {
    return `
    INSERT INTO preinspeccion_reporte (
        preinspeccionId,
        fecha,
        compra,
        proveedor,
        cliente,
        productoId,
        producto,
        descripcion,
        costounitariocompleto,
        costo,
        precio,
        utilidad,
        cantidad,
        valorCompra,
        cantidadPorNacionalizar,
        cantidadNacionalizada,
        porcentajeNacionalizado,
        prorrateo,
        compraId,
        proveedorId,
        clienteId,
        gastos_administrativos,
        gastos_administrativos_porcentaje,
        gastos_aduaneros_y_tributarios,
        gastos_aduaneros_y_tributarios_porcentaje,
        gastos_comerciales,
        gastos_comerciales_porcentaje,
        gastos_de_destino,
        gastos_de_destino_porcentaje,
        gastos_de_manejo_y_logística,
        gastos_de_manejo_y_logística_porcentaje,
        gastos_de_seguro,
        gastos_de_seguro_porcentaje,
        gastos_de_transporte,
        gastos_de_transporte_porcentaje,
        gastos_financieros,
        gastos_financieros_porcentaje,
        gastos_operativos,
        gastos_operativos_porcentaje,
        otros,
        otros_porcentaje,
        antidumping,
        antidumping_porcentaje,
        arancel,
        arancel_porcentaje,
        iva,
        iva_porcentaje,
        ultraprocesados,
        ultraprocesados_porcentaje,
        totalGastos,
        totalTributos,
        totalGastosImpuestos,
        costoUnitarioGasto,
        costoUnitarioGastoImpuesto,
        costoUnitarioImpuesto,
        costoUnitarioCompletoCalculado,
        embarque,
        embarqueId,
        gastos_costos_indirectos,
        gastos_costos_indirectos_porcentaje
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
       ;
}

module.exports = { insertPreinspectionReportQuery };